-- SHIFT CMS schema
-- Run once in Supabase SQL Editor for project pevjzfpoilljucmtdxrh.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.articles (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title_lt text not null default '',
  title_en text not null default '',
  excerpt_lt text not null default '',
  excerpt_en text not null default '',
  content_lt text not null default '',
  content_en text not null default '',
  image_url text not null default '',
  seo_title_lt text not null default '',
  seo_title_en text not null default '',
  seo_description_lt text not null default '',
  seo_description_en text not null default '',
  social_image_url text not null default '',
  scheduled_at timestamptz,
  published_at timestamptz,
  status text not null default 'draft' check (status in ('draft', 'published')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title_lt text not null default '',
  title_en text not null default '',
  summary_lt text not null default '',
  summary_en text not null default '',
  description_lt text not null default '',
  description_en text not null default '',
  goal_lt text not null default '',
  goal_en text not null default '',
  audience_lt text not null default '',
  audience_en text not null default '',
  activities_lt text not null default '',
  activities_en text not null default '',
  outcomes_lt text not null default '',
  outcomes_en text not null default '',
  programme text not null default '',
  project_year text not null default '',
  project_code text not null default '',
  partner_name text not null default '',
  image_url text not null default '',
  gallery_urls text not null default '',
  document_links text not null default '',
  seo_title_lt text not null default '',
  seo_title_en text not null default '',
  seo_description_lt text not null default '',
  seo_description_en text not null default '',
  social_image_url text not null default '',
  scheduled_at timestamptz,
  published_at timestamptz,
  featured boolean not null default false,
  status text not null default 'draft' check (status in ('draft', 'published')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  id text primary key default 'main',
  hero_title_lt text not null default 'Nuo vieno žmogaus iki startuolio',
  hero_title_en text not null default 'From solo work to startup success.',
  hero_text_lt text not null default '',
  hero_text_en text not null default '',
  hero_image_url text not null default '',
  impact_projects integer not null default 5,
  impact_countries integer not null default 3,
  impact_participants integer not null default 30,
  updated_at timestamptz not null default now()
);

insert into public.site_settings (id) values ('main') on conflict (id) do nothing;

create table if not exists public.partners (
  id uuid primary key default gen_random_uuid(),
  name text not null default '',
  logo_url text not null default '',
  website_url text not null default '',
  sort_order integer not null default 0,
  is_visible boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.inquiries (
  id uuid primary key default gen_random_uuid(),
  name text not null default '',
  email text not null default '',
  organization text not null default '',
  topic text not null default 'general',
  message text not null default '',
  language text not null default 'en',
  status text not null default 'new' check (status in ('new', 'read', 'replied', 'archived')),
  internal_notes text not null default '',
  assignee text not null default '',
  tags text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  path text not null,
  created_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists articles_touch_updated_at on public.articles;
create trigger articles_touch_updated_at before update on public.articles
for each row execute function public.touch_updated_at();
drop trigger if exists projects_touch_updated_at on public.projects;
create trigger projects_touch_updated_at before update on public.projects
for each row execute function public.touch_updated_at();
drop trigger if exists settings_touch_updated_at on public.site_settings;
create trigger settings_touch_updated_at before update on public.site_settings
for each row execute function public.touch_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email) values (new.id, new.email)
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.articles enable row level security;
alter table public.projects enable row level security;
alter table public.site_settings enable row level security;
alter table public.partners enable row level security;
alter table public.inquiries enable row level security;
alter table public.page_views enable row level security;

drop policy if exists "profiles own row" on public.profiles;
create policy "profiles own row" on public.profiles for select to authenticated
using ((select auth.uid()) = id);
drop policy if exists "profiles own update" on public.profiles;
create policy "profiles own update" on public.profiles for update to authenticated
using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

drop policy if exists "public published articles" on public.articles;
create policy "public published articles" on public.articles for select to anon, authenticated
using (status = 'published' and (scheduled_at is null or scheduled_at <= now()));
drop policy if exists "admins manage articles" on public.articles;
create policy "admins manage articles" on public.articles for all to authenticated
using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin))
with check (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin));

drop policy if exists "public published projects" on public.projects;
create policy "public published projects" on public.projects for select to anon, authenticated
using (status = 'published' and (scheduled_at is null or scheduled_at <= now()));
drop policy if exists "admins manage projects" on public.projects;
create policy "admins manage projects" on public.projects for all to authenticated
using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin))
with check (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin));

drop policy if exists "public read settings" on public.site_settings;
create policy "public read settings" on public.site_settings for select to anon, authenticated using (true);
drop policy if exists "admins manage settings" on public.site_settings;
create policy "admins manage settings" on public.site_settings for all to authenticated
using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin))
with check (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin));

drop policy if exists "public visible partners" on public.partners;
create policy "public visible partners" on public.partners for select to anon, authenticated using (is_visible = true);
drop policy if exists "admins manage partners" on public.partners;
create policy "admins manage partners" on public.partners for all to authenticated
using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin))
with check (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin));

drop policy if exists "public create inquiries" on public.inquiries;
create policy "public create inquiries" on public.inquiries for insert to anon, authenticated with check (true);
drop policy if exists "admins manage inquiries" on public.inquiries;
create policy "admins manage inquiries" on public.inquiries for all to authenticated
using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin))
with check (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin));

drop policy if exists "public create page views" on public.page_views;
create policy "public create page views" on public.page_views for insert to anon, authenticated with check (true);
drop policy if exists "admins read page views" on public.page_views;
create policy "admins read page views" on public.page_views for select to authenticated
using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin));

insert into storage.buckets (id, name, public)
values ('site-media', 'site-media', true)
on conflict (id) do update set public = true;

drop policy if exists "public read site media" on storage.objects;
create policy "public read site media" on storage.objects for select to public
using (bucket_id = 'site-media');
drop policy if exists "admins upload site media" on storage.objects;
create policy "admins upload site media" on storage.objects for insert to authenticated
with check (bucket_id = 'site-media' and exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin));
drop policy if exists "admins update site media" on storage.objects;
create policy "admins update site media" on storage.objects for update to authenticated
using (bucket_id = 'site-media' and exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin))
with check (bucket_id = 'site-media' and exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin));
drop policy if exists "admins delete site media" on storage.objects;
create policy "admins delete site media" on storage.objects for delete to authenticated
using (bucket_id = 'site-media' and exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin));
